AWSTemplateFormatVersion: '2010-09-09'
Description: CloudWatch monitoring resources for Travel Planner (SNS topic + dashboard + basic alarms)

Parameters:
  AlarmEmail:
    Type: String
    Default: ""
    Description: Optional email to subscribe for alarms (leave blank to skip subscription)
  DynamoDBUsersTableName:
    Type: String
    Default: ""
    Description: Optional users DynamoDB table name (leave blank to skip users alarm)
  DynamoDBItinerariesTableName:
    Type: String
    Default: ""
    Description: Optional itineraries DynamoDB table name (leave blank to skip itineraries alarm)

Conditions:
  HasAlarmEmail: !Not [ !Equals [ !Ref AlarmEmail, "" ] ]
  HasDDBUsersTable: !Not [ !Equals [ !Ref DynamoDBUsersTableName, "" ] ]
  HasDDBItinerariesTable: !Not [ !Equals [ !Ref DynamoDBItinerariesTableName, "" ] ]

Resources:
  MonitoringTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: travel-planner-monitoring-topic

  AlarmEmailSubscription:
    Type: AWS::SNS::Subscription
    Condition: HasAlarmEmail
    Properties:
      TopicArn: !Ref MonitoringTopic
      Protocol: email
      Endpoint: !Ref AlarmEmail

  Dashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub "travel-planner-dashboard-${AWS::AccountId}"
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "text",
              "x": 0,
              "y": 0,
              "width": 24,
              "height": 3,
              "properties": {
                "markdown": "# Travel Planner - Monitoring Dashboard\nThis dashboard monitors Elastic Beanstalk backend, DynamoDB, CloudFront, and S3 services."
              }
            }
          ]
        }

  DynamoDBUsersThrottlingAlarm:
    Condition: HasDDBUsersTable
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "trip-planner-dynamodb-users-throttling-${AWS::AccountId}"
      AlarmDescription: "DynamoDB throttling detected on users table"
      Namespace: AWS/DynamoDB
      MetricName: ThrottledRequests
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: TableName
          Value: !If [ HasDDBUsersTable, !Ref DynamoDBUsersTableName, "" ]
      AlarmActions:
        - !Ref MonitoringTopic

  DynamoDBItinerariesThrottlingAlarm:
    Condition: HasDDBItinerariesTable
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "trip-planner-dynamodb-itineraries-throttling-${AWS::AccountId}"
      AlarmDescription: "DynamoDB throttling detected on itineraries table"
      Namespace: AWS/DynamoDB
      MetricName: ThrottledRequests
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: TableName
          Value: !If [ HasDDBItinerariesTable, !Ref DynamoDBItinerariesTableName, "" ]
      AlarmActions:
        - !Ref MonitoringTopic

  CloudFront5xxAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "trip-planner-cloudfront-5xx-${AWS::AccountId}"
      AlarmDescription: "CloudFront 5XX error rate exceeded threshold"
      Namespace: AWS/CloudFront
      MetricName: 5xxErrorRate
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 1
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: DistributionId
          Value: !ImportValue travel-planner-frontend-cf-DistributionId
      AlarmActions:
        - !Ref MonitoringTopic

  # Elastic Beanstalk Health Monitoring
  EBHealthAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "trip-planner-eb-health-${AWS::AccountId}"
      AlarmDescription: "Elastic Beanstalk environment health degraded"
      Namespace: AWS/ElasticBeanstalk
      MetricName: EnvironmentHealth
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 1
      ComparisonOperator: LessThanThreshold
      Dimensions:
        - Name: EnvironmentName
          Value: travel-planner-prod
      AlarmActions:
        - !Ref MonitoringTopic

  EBInstanceHealthAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "trip-planner-eb-instance-health-${AWS::AccountId}"
      AlarmDescription: "Elastic Beanstalk instance health issues detected"
      Namespace: AWS/ElasticBeanstalk
      MetricName: InstanceHealth
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 1
      ComparisonOperator: LessThanThreshold
      Dimensions:
        - Name: EnvironmentName
          Value: travel-planner-prod
      AlarmActions:
        - !Ref MonitoringTopic

Outputs:
  MonitoringTopicArn:
    Value: !Ref MonitoringTopic
    Export:
      Name: travel-planner-monitoring-topic-arn

  DashboardURL:
    Description: CloudWatch dashboard URL
    Value: !Sub "https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=travel-planner-dashboard-${AWS::AccountId}"
    Export:
      Name: travel-planner-monitoring-dashboard-url
