AWSTemplateFormatVersion: '2010-09-09'
Description: Create 6 IAM users + one group that can Assume the team roles (ProjectAdmin, BackendDeployer, FrontendPublisher, Observer, SecretsAdmin).

Parameters:
  TeamUserNames:
    Type: CommaDelimitedList
    Description: "ali,jasper,lubai,links,simin,ziqi"

Resources:
  MembersGroup:
    Type: AWS::IAM::Group
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      GroupName: !Sub "trip-planner-members-${AWS::AccountId}"

  # Policy that lets members assume the five function roles
  AllowAssumeTeamRolesPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "TP-AllowAssumeTeamRoles-${AWS::AccountId}"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Resource:
              - !Sub "arn:aws:iam::${AWS::AccountId}:role/tp-BackendDeployer-${AWS::AccountId}"
              - !Sub "arn:aws:iam::${AWS::AccountId}:role/tp-FrontendPublisher-${AWS::AccountId}"
              - !Sub "arn:aws:iam::${AWS::AccountId}:role/tp-Observer-${AWS::AccountId}"
              - !Sub "arn:aws:iam::${AWS::AccountId}:role/tp-SecretsAdmin-${AWS::AccountId}"
      Groups:
        - !Ref MembersGroup

  # Policy for basic AWS console access (MFA optional)
  BasicConsoleAccessPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "TP-BasicConsoleAccess-${AWS::AccountId}"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - iam:GetUser
              - iam:ListMFADevices
              - iam:ListVirtualMFADevices
              - iam:EnableMFADevice
              - iam:ResyncMFADevice
              - iam:DeactivateMFADevice
              - iam:DeleteVirtualMFADevice
              - iam:CreateVirtualMFADevice
              - iam:ChangePassword
              - iam:GetLoginProfile
              - iam:UpdateLoginProfile
            Resource: "*"
      Groups:
        - !Ref MembersGroup

  # Policy for AWS console access (no MFA required)
  ConsoleAccessPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "TP-ConsoleAccess-${AWS::AccountId}"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - iam:ListAccountAliases
              - iam:GetAccountSummary
              - iam:ListUsers
              - iam:ListGroups
              - iam:ListRoles
              - iam:ListPolicies
            Resource: "*"
      Groups:
        - !Ref MembersGroup

  # Policy for viewing AWS services (read-only access)
  ReadOnlyAccessPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "TP-ReadOnlyAccess-${AWS::AccountId}"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              # EC2 read-only
              - ec2:Describe*
              - ec2:Get*
              - ec2:List*
              # S3 read-only
              - s3:GetObject
              - s3:ListBucket
              - s3:GetBucketLocation
              - s3:GetBucketVersioning
              # DynamoDB read-only
              - dynamodb:DescribeTable
              - dynamodb:ListTables
              - dynamodb:Scan
              - dynamodb:Query
              - dynamodb:GetItem
              # CloudFormation read-only
              - cloudformation:Describe*
              - cloudformation:List*
              - cloudformation:Get*
              # CloudWatch read-only
              - cloudwatch:Describe*
              - cloudwatch:Get*
              - cloudwatch:List*
              # SNS read-only
              - sns:GetTopicAttributes
              - sns:ListTopics
              - sns:ListSubscriptions
              # Secrets Manager read-only
              - secretsmanager:DescribeSecret
              - secretsmanager:ListSecrets
              # Load Balancer read-only
              - elasticloadbalancing:Describe*
              # CloudFront read-only
              - cloudfront:GetDistribution
              - cloudfront:ListDistributions
            Resource: "*"
      Groups:
        - !Ref MembersGroup

  User1:
    Type: AWS::IAM::User
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      UserName: !Select [0, !Ref TeamUserNames]
      Groups: [ !Ref MembersGroup ]
      Tags:
        - { Key: Project, Value: TripPlanner }
        - { Key: Team, Value: Members }

  User2:
    Type: AWS::IAM::User
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      UserName: !Select [1, !Ref TeamUserNames]
      Groups: [ !Ref MembersGroup ]
      Tags:
        - { Key: Project, Value: TripPlanner }
        - { Key: Team, Value: Members }

  User3:
    Type: AWS::IAM::User
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      UserName: !Select [2, !Ref TeamUserNames]
      Groups: [ !Ref MembersGroup ]
      Tags:
        - { Key: Project, Value: TripPlanner }
        - { Key: Team, Value: Members }

  User4:
    Type: AWS::IAM::User
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      UserName: !Select [3, !Ref TeamUserNames]
      Groups: [ !Ref MembersGroup ]
      Tags:
        - { Key: Project, Value: TripPlanner }
        - { Key: Team, Value: Members }

  User5:
    Type: AWS::IAM::User
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      UserName: !Select [4, !Ref TeamUserNames]
      Groups: [ !Ref MembersGroup ]
      Tags:
        - { Key: Project, Value: TripPlanner }
        - { Key: Team, Value: Members }

  User6:
    Type: AWS::IAM::User
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      UserName: !Select [5, !Ref TeamUserNames]
      Groups: [ !Ref MembersGroup ]
      Tags:
        - { Key: Project, Value: TripPlanner }
        - { Key: Team, Value: Members }

Outputs:
  GroupName:
    Description: IAM group for team members
    Value: !Ref MembersGroup
  UserArns:
    Description: Comma-separated ARNs of the six users
    Value: !Join
      - ","
      - [ !GetAtt User1.Arn, !GetAtt User2.Arn, !GetAtt User3.Arn, !GetAtt User4.Arn, !GetAtt User5.Arn, !GetAtt User6.Arn ]
