AWSTemplateFormatVersion: '2010-09-09'
Description: Secrets Manager for Trip Planner - JWT, Database, API keys, and other sensitive configuration.

Parameters:
  JwtSecretKey:
    Type: String
    Default: "CGy0qUYRtpU+Fy54cF0fSNYsl1FXzuJ2hb3O"
    Description: JWT secret key for token signing
    NoEcho: true
  
  JwtExpMinutes:
    Type: Number
    Default: 480
    Description: JWT token expiration time in minutes

Resources:
  # JWT Configuration Secret
  JwtSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: trip-planner/jwt
      Description: JWT configuration for authentication
      SecretString: !Sub |
        {
          "SECRET_KEY": "${JwtSecretKey}",
          "JWT_EXP_MINUTES": "${JwtExpMinutes}"
        }
      Tags:
        - Key: Project
          Value: trip-planner
        - Key: Service
          Value: authentication
        - Key: Environment
          Value: production

  # Application Configuration Secret
  AppConfigSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: trip-planner/app-config
      Description: Application configuration settings
      SecretString: !Sub |
        {
          "APP_NAME": "Intelligent Travel Planner",
          "APP_VERSION": "1.0.0",
          "DEBUG": "false",
          "LOG_LEVEL": "INFO"
        }
      Tags:
        - Key: Project
          Value: trip-planner
        - Key: Service
          Value: application
        - Key: Environment
          Value: production

  # Third-party API Keys Secret
  ApiKeysSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: trip-planner/api-keys
      Description: Third-party API keys for external services
      SecretString: !Sub |
        {
          "WEATHER_API_KEY": "your-weather-api-key",
          "MAPS_API_KEY": "your-maps-api-key",
          "OPENAI_API_KEY": "your-openai-api-key"
        }
      Tags:
        - Key: Project
          Value: trip-planner
        - Key: Service
          Value: external-apis
        - Key: Environment
          Value: production

  # S3 Configuration Secret
  S3ConfigSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: trip-planner/s3-config
      Description: S3 bucket configuration
      SecretString: !Sub |
        {
          "ASSETS_BUCKET": "travel-planner-assets-${AWS::AccountId}-lz",
          "FRONTEND_BUCKET": "travel-planner-frontend-${AWS::AccountId}-lz",
          "AWS_REGION": "${AWS::Region}"
        }
      Tags:
        - Key: Project
          Value: trip-planner
        - Key: Service
          Value: storage
        - Key: Environment
          Value: production

  # SNS Configuration Secret
  SnsConfigSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: trip-planner/sns-config
      Description: SNS topic ARNs for notifications
      SecretString: !Sub |
        {
          "NOTIFICATIONS_TOPIC_ARN": "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:trip-planner-notifications",
          "ALERTS_TOPIC_ARN": "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:trip-planner-alerts"
        }
      Tags:
        - Key: Project
          Value: trip-planner
        - Key: Service
          Value: notifications
        - Key: Environment
          Value: production

  # DynamoDB Configuration Secret
  DynamoDbConfigSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: trip-planner/dynamodb-config
      Description: DynamoDB table names and configuration
      SecretString: !Sub |
        {
          "USERS_TABLE": "Users",
          "ITINERARIES_TABLE": "Itineraries",
          "ATTRACTIONS_TABLE": "Attractions",
          "RECOMMENDATIONS_TABLE": "Recommendations",
          "AWS_REGION": "${AWS::Region}"
        }
      Tags:
        - Key: Project
          Value: trip-planner
        - Key: Service
          Value: database
        - Key: Environment
          Value: production

Outputs:
  JwtSecretArn:
    Description: ARN of JWT configuration secret
    Value: !Ref JwtSecret
    Export:
      Name: trip-planner-jwt-secret-arn
  
  AppConfigSecretArn:
    Description: ARN of application configuration secret
    Value: !Ref AppConfigSecret
    Export:
      Name: trip-planner-app-config-secret-arn
  
  ApiKeysSecretArn:
    Description: ARN of API keys secret
    Value: !Ref ApiKeysSecret
    Export:
      Name: trip-planner-api-keys-secret-arn
  
  S3ConfigSecretArn:
    Description: ARN of S3 configuration secret
    Value: !Ref S3ConfigSecret
    Export:
      Name: trip-planner-s3-config-secret-arn
  
  SnsConfigSecretArn:
    Description: ARN of SNS configuration secret
    Value: !Ref SnsConfigSecret
    Export:
      Name: trip-planner-sns-config-secret-arn
  
  DynamoDbConfigSecretArn:
    Description: ARN of DynamoDB configuration secret
    Value: !Ref DynamoDbConfigSecret
    Export:
      Name: trip-planner-dynamodb-config-secret-arn
